#! /bin/sh

#### MONITORS ####

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11

#### AUTOSTART ####

# keybinds
killall sxhkd; sxhkd &

# polybar
bash $HOME/.config/polybar/launchBSPWM.sh &

# picom
killall picom; picom --config $HOME/.config/picom/picom.conf &

# automatic screen lock
pkill -f "watch -n 120 /home/ferry/Documents/scripts/lockScreenInactive.sh"; watch -n 120 $HOME/Documents/scripts/lockScreenInactive.sh&

#### COMMANDS ####

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          0
bspc config pointer_motion_interval 7

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# focus on hover
bspc config focus_follows_pointer true


#### Window Rules ####

bspc rule -a Pavucontrol state=floating
bspc rule -a Enpass state=floating

bspc rule -a galculator state=floating


# Desktop 8
bspc rule -a Discord desktop=VIII
bspc rule -a Discord focus=off
bspc rule -a Discord follow=off

# Desktop 9
bspc rule -a "Spotify Premium" desktop=IX
bspc rule -a "Spotify Premium" focus=off
bspc rule -a "Spotify Premium" follow=off

# Desktop 10
bspc rule -a Transmission-gtk desktop=X
bspc rule -a Transmission-gtk focus=off
bspc rule -a Transmission-gtk follow=off

bspc rule -a obs desktop=X
bspc rule -a obs focus=off
bspc rule -a obs follow=off


# For the jojo alias
bspc rule -a Alacritty:coolEqualizer state=floating
bspc rule -a Alacritty:coolEqualizer --flag sticky=on
bspc rule -a Alacritty:coolEqualizer focus=off


bspc rule -a mplayer2 state=floating
bspc rule -a jetbrains-toolbox state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a emacs state=tiled


# this is for java applications
wmname LG3D

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
